name: televolution_native
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_appwrite: ^12.1.0
  http: ^1.2.2
  jaspr: ^0.15.1
  jaspr_material: ^0.1.7
  jaspr_riverpod: ^0.3.14
  jaspr_router: ^0.5.1
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  jaspr_builder: ^0.15.1
  jaspr_tailwind: ^0.3.0
  jaspr_web_compilers: ^4.0.10
  lints: ^5.0.0

jaspr:
  mode: client

